### ISSUE TITLE
multistore - wrong Terminal Display priority 

### ISSUE THREAD

**Issue by abdullacm** [AltaPay/plugin-prestashop#91]
When editing a terminal in a multistore, the display priority field incorrectly displays values because the getTerminals method retrieves terminals based on shop_id = 1. To rectify this, we need to pass the current shop ID, like `getTerminals($this->context->shop->id)`, for it to function correctly.

`$totalTerminals = count(Altapay_Models_Terminal::getTerminals()); `
change this to
`$totalTerminals = count(Altapay_Models_Terminal::getTerminals($this->context->shop->id));`

**Comment by Zpolonius** [comment]
Thank you @abdullacm!
I have added it to our backlog.

**Comment by BushraAsif** [comment]
@abdullacm, this has been added in the latest release.
